// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "F2DHbnipEjk5NqcMfJ4h8pu19cV7xQpM1C2MZBB3ZVZ9";
export const coinVault = "9a3XxGckfZAErcJk18McUC3kR6ocbBNL2kqPU8jY6eQ2";
export const pcVault = "9xKDc4YU8LxTA4bt3saMrJ7s2d2XXBwzBgc3d9yvedb7";
export const coinMint = "21KEMaXZmCUcXgeUaxsnbtEu28xrTCbhhbfiimdbRVww";
export const pcMint = "DJMLyvYA7aJiZrK8ye2zsXdFTc3myV5N7LsDZ26tPZCQ";
export const bidsPda = "Bzc1wyc1yAZhdMHKULAmgem4VA41zNPCUpZK7aCaJaiR";
export const asksPda = "DikANYx6cmDNbdK7QKAh3wPpjR237oux6d28kAPjQb9j";
export const reqQPda = "7dvZqx2PBHEr5rAS8yi56RJZXbomumfWDSKmyicFq4W6";
export const eventQPda = "FEA6DQHJvEKEDLc3qetWamqXWKLE3EPp8LitG6PuuYhY";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
