// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "jfbViWxrJ3eFeN3J7K9aCaTL6onKNkvFWRzLeJ64jAH";
export const coinVault = "5EUomz5o4nQjHS36KQ5XMbGB3aFzq6sv167JS59WTUoY";
export const pcVault = "EKB2HxPvUp1CgfwGP8SmAUxU3sxq9BnyUErqocSfxxF8";
export const coinMint = "9NkWiwvBeCiAXi6q6z5jRhTaaCLgL5sxBGmBbX1y1mu5";
export const pcMint = "GjE1xeAu648SkY7zxzLUZLDRfcrsyuimm5zBxGKYet1T";
export const bidsPda = "6c3GkWYBNA7HVhQLZXHE1Wvhx7WDPNEnmvjPm3F2mjS5";
export const asksPda = "6YaZLLDNuKHrUTd7pv3Dw9Qa3pqDDUw83hWcuuw9ogV5";
export const reqQPda = "4LWHGjsGD93v3KzjPTsbgz4LAiAjBHVds3pxstaLqrb2";
export const eventQPda = "D5hB7ATeDK2wbeGqBTWh8vyEvZWGhNhc7Sf2nX885hs3";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
