// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "FdAnptZ1oiPEW1b3CNMDkx1V67kiAz5UzRNQ3xG4Kyhm";
export const coinVault = "Hosxq1vgv88L4cPnseyZUuPP2LdHkJAnJhA1hYjshEG2";
export const pcVault = "9RGGUy7vPSqF9t2HE9HGEbvcBtEWgC8qbvW88aMRqS48";
export const coinMint = "DYB8XdZZHuJ2eWRAwY78ezDLUjKEZiZiCaNAHPuvRrtN";
export const pcMint = "7R7G9Fx3coUHNz6LJkC6dXUiVZ3VaURCzj8iPjkU7ztx";
export const bidsPda = "6pb4Puk8vR47pYoR6s7dvfEvJeZ9aVrtSGkAztKK3dqi";
export const asksPda = "5D2yyUDjWtvMT9o6TLpqTYT1ETv8Cj9mf4ah2ba4ED5n";
export const reqQPda = "4wigivuPxq2ML91BdU4AgxZxzGeSB5rZL7zaHnP13yWt";
export const eventQPda = "52VrCm5tDemhrAd3Mvfa5TRPTmWAXLXDAS3CQHcRGPq4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
