// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "HoqC6EU63wkdpqfsmKX4pQQkvWPBvGqVu81zfRAe6bqo";
export const coinVault = "7WCVUZCd8ZFtrc7PMLgGfgiGsZY8f7NNKzmxmnMt8RB5";
export const pcVault = "zZDzLitMnafwtmZgkJDzc6U1qrmmmLSPS53NTdbx7Vy";
export const coinMint = "8K1XHpi8Y8n8j57KYvGTmpxxZEoiNamMVVf56M9BWbzt";
export const pcMint = "HmuUSZUCGUu7h9yqCVRemvjrJr1weU6Y9QrLmWvuxTAx";
export const bidsPda = "6cvWoEDLnJMea5M8xRB2HYLRKiVHeFY5JGzMZhjdUpug";
export const asksPda = "6mc11QH8mrN792GTxnQcdv6Fa6UfeVbKfCzyqfxR39s1";
export const reqQPda = "2HmQSjmwdts8Xh3eeMiUfT6zUKH6pYNggccDarSy9xdm";
export const eventQPda = "9SWdbDzdo95QW3ciw1Q2UbfqTQgc3so3zynvCF8j2Swp";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
