// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "BL9LWDsx3FgbsEvBFq1Nt6dFwx4juQeg7bNCQPpur8nh";
export const coinVault = "D5XYqwgpkYTW9XiAwsG66YpVZNYRhzuBfaXtebGqStXC";
export const pcVault = "3FW8vX9D4jhc4t12HB3UxnirgU66d6Jbo4fwoaJhrg1v";
export const coinMint = "2bHDbknZNAEcm4CxqZEaQ72qjW1VcnPtTwLRmSLEukL4";
export const pcMint = "6XvxrZrDKPKXYy8i1S9MpCQJ9btxSUYPxkqLBU1uN3TL";
export const bidsPda = "MBiwQWzGjKRFVD7AQgQGKfxc5nhSTQUeNg4uANbq9Z4";
export const asksPda = "Dou4ixfdT59fS1gq2kDfRMFiVgbvWJ19aSsswXknfAB8";
export const reqQPda = "AuE5VqFuhi2TfgqEnDuPtBBffDawfjXDq8w7yFyXY9P1";
export const eventQPda = "HXgaNgpZnNrEvvoY6dr41AMup6oUJeVcPHQSsbECSVtM";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
