// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "3ABNr2q48dUcAWk8ZdsU9jXzYUpA4uiFFHjWBVtny3PS";
export const coinVault = "BQf4PauTkvAnSKnz8q8VidMokFRvBpSUzNoDZENpGcEd";
export const pcVault = "4DE39Hob2QifaP79vJJuk1ik4CML5MxLTdojZSABvHyk";
export const coinMint = "C96xfkAsRx2T48fSG2oRrmMVJbiWcuPdgCQY9ma4xrvF";
export const pcMint = "8KA2zXCqaHCCvChx8ovGymnmH4UYf4UKxf32eMmyqKLU";
export const bidsPda = "2LG7BdhGXXQuX5uBVGKpBwXZFcUp4RWiZqYhkm5Aq4cT";
export const asksPda = "AGuJYLRKNuoC5WiUPE5gxFu9W3njRTCpj9NZqhUQXPGw";
export const reqQPda = "6JvK4Mnb2j8QoqjETMLFifT71puUi7necPiaQJecf5VR";
export const eventQPda = "9Ruy8i7KhhioRjPStWoork7WPBiUaydSTixFjWZ5b6cV";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
