// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "79EgGaKZkF85FQoLWdQqWtsuK4aMFNbDVffkgW7iKNQu";
export const coinVault = "6n7odts487gi1A9XWE513K5qWmxsAkVonB7e4BwU41wk";
export const pcVault = "AqaK6ixFMmiBMD4HCNrL8b6fnh2GgCEje3zqzjZzH89s";
export const coinMint = "9wQooC7f1hhZEA2ZZsiu8H8Czs7nFTPzrTeHZeh8kuod";
export const pcMint = "Hme6KERppWhAne8e3M4DT98fTmDvQSKJBgvcVx7it5Yc";
export const bidsPda = "7HG5CG9Er66nUbAuoHU3eHz4Th4CSftMpTUaA3s8tHge";
export const asksPda = "Wb5K2WB74DV2tyWVEDUJezf1Z9pEPNouVpYNgjHZySA";
export const reqQPda = "5evHyGCh23qtXhXUsv5MvrLywq9RueqqGuiFKRwRgmRF";
export const eventQPda = "EfYMaYT4Vafemh9X8yLQ1we1dzU7ixhfNudTYasaVxQG";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
