// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "2HtPYfYZ5zjVxgbQ9oxtpMr8Trczu4r1KmE6xSBx7Ksw";
export const coinVault = "13bAjyKSocFVNqjEKnu91oQSBgKAGsWFRnxzh3pYcED8";
export const pcVault = "7cDhRjUxJe3MebEWZjNsUkRxDriuGDh64CFXP8euQDQ9";
export const coinMint = "7obS5M9EXBdjS448zFneb5spky1JuNrX4Draxevk6hiT";
export const pcMint = "52sULa19y7Lr7H4xPj3ArK54j5HsV2ibdyNdUM29TYK2";
export const bidsPda = "3nxvzqa5QTZ36Q3grMeHrQ1qncn6nSWFE999WD6unFzj";
export const asksPda = "61DbnnZdxhcSBtQ75MBPCM6rdwdcfoQWznEH7hMimH6t";
export const reqQPda = "2pkiZkV1fiQ5uMXvk9Ny7ddcbMagP33FYMCqFNomsU1F";
export const eventQPda = "C7Uvw7ywvkeeLhQ43J1hBacoNP8m3U9XnNhaU5MyrE7M";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
