// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "yChp7aMfxqbn277jm38cWoBSinKwLrs2PF6nxWfQA2t";
export const coinVault = "5LKbCzLvadgDkf1rtX3YyhQnUz1CSEowD4qniAFcvd2j";
export const pcVault = "DfFqXzKGgBLpoNmk98xposJ97vhb87hwN5VqdGpRHLf9";
export const coinMint = "7unFW5H6xdQQEcfWaJKGDjxrRNqV9GJLTSFWAGaAxFCy";
export const pcMint = "8SdW9CLfnw7devuwXvuNJBbdTULPfsH9Gs4xvqDDJ8cY";
export const bidsPda = "9sZKg1b21kncyHaH4MQFxHmVj52mKCF8ro1p3a5S3Bgo";
export const asksPda = "4kdT5BwX3FUrKfA9SBjwDoiRrEuo3KRMotrCvUzWbHcj";
export const reqQPda = "6vHQeQNp46oL3e9xTcugX3QiFXNVU9VQ3Tnjjh71EKX";
export const eventQPda = "9un5Mdztworda9D9KRo39AvY2qExX3WdehJNUg6L1Fr9";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
