// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "Eu6tLYhbfv4KfRYoiwp3mMS1ejnSJNJWuYq9de1RMBfw";
export const coinVault = "B2m5VTzmVRFyzrhDcqUUhzYb3UACZQoB77kGoPrH7ifi";
export const pcVault = "Gh5DBA3i3o7KCCrnndQ3jDuE56EBc7n4EFrbBuFf9s1n";
export const coinMint = "K8iHs6pTNZtPNDM5EhujTdqaDhLpegZgwUvFn5iSpSz";
export const pcMint = "4hnvbbspPmfUS8E9seJFocK4yBHgghFa1qLL8pG9UsYT";
export const bidsPda = "7Seq7cs4VhCqauAwSnMpWbX9uxuESKiWqFmr3t6GYS9p";
export const asksPda = "5wxZpkShRD9gQP7fBj4Dt2FV4uVZJuNArheUBHGmTv57";
export const reqQPda = "C5CiCSPermHDVztxT81iPrd1CtqiedB7kUZsFr2gcamv";
export const eventQPda = "99L1p3QjWxyQ7Yq55Qyob7LXWrbLTGMVuh4AkXQmGHgT";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
