// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "FXENiP7CJAxKovzAaymyhd1B3eDo2RZd2WRQjYhM6m3k";
export const coinVault = "2jFE2JdFVLwQrbVsVtiDTLpmLh3MXGtqZynCXQvhoX9k";
export const pcVault = "CFpKo1cssKAi6PX9dDNonCwWWVVS48gztdPnm5W7GERR";
export const coinMint = "CK7TW4kfgDtQ7tJwPHa7tTCAsEW5vRYTQFymS7AJmuZn";
export const pcMint = "8Hexvv5j4dDmX6e88R8ETB2LMWNsS5RVeqPEwphN3cnd";
export const bidsPda = "6uVjXgAsRxwHJhYSpdwmigUVWDQ9dChXe8itGHdM2U9";
export const asksPda = "CZr8QwkaTUCyXyUo5DrQ4mLaV6FUztAUdjafajbr79PE";
export const reqQPda = "6mfxif1gmMMp3b4btmjNtF76QoX7T3XvexpDsSXccJCi";
export const eventQPda = "2qtgYGsEzb78XpULp2AMhWuQv55BJguRYzNadvrJhfF7";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
