// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "HwMLh1cFyzXJje6cujpSRSPwYichNY5r15RAcYfk24fZ";
export const coinVault = "CaprfAKuoBGb25eZpSq6jbPxKyFJgM8fcavBbU4uLD9d";
export const pcVault = "3rGNYxLJCVRvM7vcP5GWU1VbxUvzd8yiQVAYbmXzDf1i";
export const coinMint = "BqfgVrjjrJZ9DMBu7WEdaoei5iwdHL29Qi6uQUhDZZz8";
export const pcMint = "398eLeHQiCw17yhQi8rkKBogYVrKHV13X1Zq2z244e5q";
export const bidsPda = "AkW5ew8d2a87zeX6UF8gCoAB4CPYYW6V7RZud1JWGanv";
export const asksPda = "81sCgbAfhmAiy5SW3Uwksyfap29KrR56X6MQXuofByyr";
export const reqQPda = "AytbMpJQY3teY4FFeAt6T1G7TpnsMHDi7qYRJye6fWLf";
export const eventQPda = "HK6KSRavGce129T2sqqUTze5EB4QStSKgaDnzvcYdMVm";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
