// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "2QNX78UmmYXedbT9vj7gfrDNTRJmdiUtCbJP4bEbTEiY";
export const coinVault = "J8zppmwd84ZLLP3eQAZLTzJEyUQqpmJgBTZS9jxEcDKi";
export const pcVault = "6boeHrmkgEWXJVwiGM3ub1VGbgHeSjJaUd6HW7dN16xH";
export const coinMint = "4XvGxR9LsyD3onYZ616kZ52fvh6Vq5yXcFkwrCv1N2pQ";
export const pcMint = "AQkn7MQRoLuSXAYZnreUYhkS9QupMQLq4bAiNTosVAvb";
export const bidsPda = "E7SiSPfdnh9UiLMU7qN5ed9AFAHpzBP1XFRFPv63o4c5";
export const asksPda = "XQKQce4XvmtrAaTWDAfx5GTd1VYsqC6dE7iBMLoPgBe";
export const reqQPda = "9UbvDop8eyNCW9eea1ZoFCnrCpSJGm3uSD7FY2R97pdw";
export const eventQPda = "E1YhTwZWJxn4rCRB8YGDVpBArCodgioj8Yft1wvkWTE6";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
