// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "DZXXkFydxZMvpg3BhZUkHhMEZhAHzyE5UKJMc3TUdTfR";
export const coinVault = "7PjYJiemn44YEcsrS6m5NC4wm1JqD46ZsMMsmJtcUg2A";
export const pcVault = "51ek8NHCzp66Vg9Nfj3q4ro9e2bxsyVaNrpcsYE4vZg5";
export const coinMint = "EsHGgqfRtfkjvTJF3kDu19JhUBJiJLFcDdm6Lg8JRLXS";
export const pcMint = "5cwSKgixMH1P7jYhu3XWML2p8vus1kKGG8FQzMmN6AvN";
export const bidsPda = "8MqYfJCM2H9n3crZmBCzjkDPycYUyzLi1emRzQe4uZu7";
export const asksPda = "GLCzCLk3eptNP98UC4NBxov9VpxixJPUs6xqrA95QTnj";
export const reqQPda = "6oMyc6nBXG6uKexuwdNFAjFHfHD6XWv6PoShX4qwXJdY";
export const eventQPda = "HmcELjT3KFuek2zjKXsHDrdyttMbxUuY9uw3pCnGxs27";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
