// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "2Bfnp7BD4UJgg9CJe7eqm3He2nnptqrqXj5WN7j5LPXJ";
export const coinVault = "F88WFkQeHaK2ne2SsNQcu3bHZ2aSSDequ48bQgzf2DKs";
export const pcVault = "HqEVWhHNsyoWoNFDjyufC9FiMHVTYEEefhF59dSdYDZ8";
export const coinMint = "GyKfa53NsxaJyJp73eNPzdP2HR7oy7GfE3PC8m3uvidP";
export const pcMint = "9G6msE5WPNnX7YQhq1E5Xj4anAme86waFKNfyFyusaTC";
export const bidsPda = "98XtepeZ1yd9PFtQHEn5CU1Ckc4nKQgBwL7fTnv9GXEH";
export const asksPda = "7d7Bp79mYSVkM3ynHyN8cpcpk4az9umbvzHZKweMr33";
export const reqQPda = "2GmfPpbRkvSeRq4km6jWV8stHMzBR6pH3oistKUVBUGS";
export const eventQPda = "2deQR1tuTza2KBPv8CGoigGjAtk973R8wJvd2RtCSXrW";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
