// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "A75p1zVnT9NjDhNTe52mVJee2gaVVmy13DEkpWq7By34";
export const coinVault = "oLSPDBZJsCcBC1s3yjBhE8c1wAsDm4KLQVXovaThox7";
export const pcVault = "Do1EaMNNVvxjshWbnDNKBWPKb2PAHw3u2DyoUerA7MG2";
export const coinMint = "Hag4zy97WZX7vexGv2suSQ22qcD6CpYcMfufAfA1S3zH";
export const pcMint = "GLnfqVEUj5X6D6m4X8gQ6hmQwNLW5PgT3DcyKMh5tRr6";
export const bidsPda = "6zhoHFndobi2TNxJttcvFLsS8sqcetRJJbK1ocmxSrMo";
export const asksPda = "GPhu6UK26AhEfzcGryn44YS7yhoKXkbEdfKivJ13t6h2";
export const reqQPda = "2Sz9ddTqZT2Ga66gG897pm4CLCexyxvA6TqqR26wzmrr";
export const eventQPda = "8p2KsgPZ2joTMCoGvCYv262VBVmRh3JdKexKeHp297zy";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
