// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "7AaFLuFbNGUqdP2KvCzo7phMrM2VscJm7AuoYEpfdpQv";
export const coinVault = "GEwd8cAZ8egY68beQ8PKVLSg9smvW9mQAHNa4pPE6w53";
export const pcVault = "9KE1hUyRwcY6M5qNRGPv9q25oL42JYaN7ZMFsHJLFxHa";
export const coinMint = "2fFx8JW74yAy3MR8FbnpimZvrbfgd6xSnVg1VLVdGnr3";
export const pcMint = "E14NEtT9igzSN4fvGw8DLmGTAVkJezNVdc6dVrNrzF2Y";
export const bidsPda = "9HjX3QKVS4M83k5pRB42hSuvw5XPDxgbSHkx6VDvhU6G";
export const asksPda = "EV6a9AoEgT2ivFbRpBPsmLg57ciTaTseifuwEeGqoswR";
export const reqQPda = "7A1j5yh1PUS6JWF5C97WAAxPUsE1PJ31SHAkQyiyF1bk";
export const eventQPda = "GmFpfthzatrNfNZ7QpP7UvUv4B9ETmJWzPZiLpFSXXNP";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
