// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "51kaVXWmx58eHB2dFdLSUyDNznmH6oHbV9p6XLs6LzrB";
export const coinVault = "9BuftdTvy6bi9RwQQqKPDtqKGKDCkNa58GN2uXC23WA1";
export const pcVault = "FVbuAxZAPRJ47pjXEpWtgk12Qq9ZXSZeuzZaDUp6Mwrt";
export const coinMint = "B73zPNrh6nNBKfSejCZ5tSWgMKJovLhosRRNZ1RjwP52";
export const pcMint = "FgEwFAoY5VSiCY5YGk8rysATzHne6sPJcdg5HVaNCe9Q";
export const bidsPda = "7bxsxFXkZaBUwWL9Tc3Esrv4xkYDUmdTL8SfHmGexERk";
export const asksPda = "9Ceu4vY39pnLYjHFkREnPyEtkUQPvXico2JCwgiCZnU";
export const reqQPda = "8TKcBcKNyrwZPXw4mH2cbqH457VkR35T5FZhLshFX5Tg";
export const eventQPda = "7jP1PHK42fCZ1G2jPpuS8fNsnF88HS6V1hozxNr4Dv4i";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
