// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "EB4sHpLpN1Zq5nR3Zu78kztNj6V77ocJHXHbGuoiCwGC";
export const coinVault = "9RodWhNnnCoKwoTnNrcbVF9oqW4b5YoGT3D9Jh2T7LiT";
export const pcVault = "ExxBwtU7bZG3UP9N9HfaNUg4qcxNpHe9joT8d6auuDcy";
export const coinMint = "BNQFtsGq4gKgpSEkZ4KQcgZvnfvUpi96WpbJ67Z5eM8V";
export const pcMint = "FHCmp2sd1nTE4Y1x7SgTdDoWPxV1whqfb262hYHay924";
export const bidsPda = "7xEZdyGaovYnTVbAHtFYFan1fZmtruJ7voJhDxiMBAu9";
export const asksPda = "7CXBRK99Vv1CxBBrtgELu6LiwPqiqaeWMSQa5KGb7ujC";
export const reqQPda = "2e5gM4aEffUzhkhuqXaj9PyvASULLPgcrSRYnZYyXzmT";
export const eventQPda = "C9DdB5FL1g8vpwjmpM3kATi1F5qwYSJHZVLc3WMf35gh";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
